WITH MAX_LEN AS (
    SELECT 
        FISH_TYPE, LENGTH,
        ROW_NUMBER() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RK
    FROM FISH_INFO
    )
SELECT 
    COUNT(I.ID) AS FISH_COUNT,
    L.LENGTH AS MAX_LENGTH,
    I.FISH_TYPE
FROM FISH_INFO AS I
JOIN MAX_LEN AS L ON I.FISH_TYPE = L.FISH_TYPE
WHERE L.RK = 1
GROUP BY I.FISH_TYPE, L.LENGTH
HAVING AVG(COALESCE(I.LENGTH,10)) >= 33
ORDER BY I.FISH_TYPE
